config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  get 'cars/accelerate'
  get 'cars/status'
  get 'cars/new_car'
  get 'cars/brake' => 'cars#brake'
  get '/' => 'cars#index'
  get 'cars/create' => 'cars#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car
  attr_accessor :speed,:make,:model
  def initialize(make=" ",model=" ", speed=0)
    @speed = speed
    @make = make
    @model = model
  end

  def accelerate()
    @speed = speed + 10
  end

  def brake()
    if @speed-7>0
      @speed = speed - 7
    else
      @speed=0
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
  end

  def new_car
    session[:car]=(Car.new(params[:make],params[:model])).to_yaml
    redirect_to '/cars/status'
  end

  def status
    @car = YAML.load(session[:car])
    @make=@car.make
    @model=@car.model
    @speed=@car.speed
  end

  def create
    @car = YAML.load(session[:car])
    @make=@car.make
    @model=@car.model
    @speed=@car.speed
  end

  def accelerate
    @car = YAML.load(session[:car])
    @car.accelerate
    session[:car] = @car.to_yaml
    redirect_to '/cars/status'
    cookies[:speed]=@car.speed
  end

  def brake
    @car = YAML.load(session[:car])
    @car.brake
    session[:car] = @car.to_yaml
    redirect_to '/cars/status'
    cookies[:speed]=@car.speed
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/create.html.erb
<h1>"HI"</h1>
The car make is <%=@make%>
The car model is <%=@model%>
The car speed is <%=@speed%>

app/views/cars/index.html.erb
<h1>Cars#index</h1>
<p>Welcome to the Car Simulator</p>
<form class="" action="/cars/new_car" method="get">
  <input type="text" name="make" value="" placeholder="Enter Make">
  <input type="text" name="model" value="" placeholder="Enter model">
  <input type="submit" name="" value="Start Simulator" >

</form>

app/views/cars/status.html.erb
<p>Welcome to status</p>


The car make is <%=@make%>
<br />
The car model is <%=@model%>
<br />
The car speed is <%=@speed%>

<%=button_to 'Accelerate That Bitch', cars_accelerate_path, method: :get %>
<%=button_to 'Stop That Bitch', cars_brake_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>